# =========================
# FRONTEND (Next.js)
# =========================

server {
    listen 80;
    server_name top-silver.ua www.top-silver.ua;

    # letsencrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # redirect to https
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name top-silver.ua www.top-silver.ua;

    ssl_certificate /etc/letsencrypt/live/top-silver.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/top-silver.ua/privkey.pem;

    location / {
        proxy_pass http://next_front:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# =========================
# BACKEND (Laravel API)
# =========================

server {
    listen 80;
    server_name api.top-silver.ua;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.top-silver.ua;

    ssl_certificate /etc/letsencrypt/live/top-silver.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/top-silver.ua/privkey.pem;

    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_pass laravel_app:9000;
        fastcgi_index index.php;
    }

    location ~ /\.ht {
        deny all;
    }
}
